version: '3.7'

networks:
  postgres-net:
    name: postgres-net
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - postgres-net
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'email@provider.com'
      PGADMIN_DEFAULT_PASSWORD: 123
    depends_on:
      - postgres
    networks:
      - postgres-net