server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  flyway:
    schemas: users
  jpa:
    properties:
      hibernate:
        default_schema: users