server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: 123
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
#  jpa:
#    properties:
#      hibernate:
#        default_schema: users
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: true
    #defaultSchema: users
    change-log: classpath:db/migration/liquibase/changelog-master.xml
    database-change-log-table: TB_DATABASE_CHANGELOG
    database-change-log-lock-table: TB_DATABASE_CHANGELOG_LOCK