CREATE SCHEMA IF NOT EXISTS SC_USERS;

CREATE TABLE SC_USERS.TB_USER(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);