CREATE TABLE SC_PRODUCTS.TB_PRODUCT(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    PRODUCT_IDENTIFIER VARCHAR NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    PRICE FLOAT NOT NULL,
    CATEGORY_ID BIGINT REFERENCES SC_PRODUCTS.TB_CATEGORY(ID)
);