server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: 123
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        default_schema: products
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: true
    change-log: classpath:db/migration/liquibase/changelog-master.xml
    database-change-log-table: TB_DATABASE_CHANGE_LOG
    database-change-log-lock-table: TB_DATABASE_CHANGE_LOG_LOCK