server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  flyway:
    schemas: products
  jpa:
    properties:
      hibernate:
        default_schema: products